"""remove duplicate target_price from user_products

Revision ID: a42ec9b45182
Revises: fa556073ef48
Create Date: 2026-05-03 07:06:20.244823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42ec9b45182'
down_revision = 'fa556073ef48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_column('target_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
