"""add target_price to user_products

Revision ID: fa556073ef48
Revises: 92bcff56b85c
Create Date: 2026-05-03 07:03:09.131442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa556073ef48'
down_revision = '92bcff56b85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_products', schema=None) as batch_op:
        batch_op.drop_column('target_price')

    # ### end Alembic commands ###
